[versions]
kotlin = "1.9.0"
kotlin-cli = "0.3.5"
kotlin-kover = "0.6.1"
ktlint = "11.2.0"
xmlutil = "0.86.1"
okio = "3.4.0"

[libraries]
kotlin-cli = { module = "org.jetbrains.kotlinx:kotlinx-cli", version.ref = "kotlin-cli" }
xmlutil-core = { module = "io.github.pdvrieze.xmlutil:core", version.ref = "xmlutil" }
xmlutil-serialization = { module = "io.github.pdvrieze.xmlutil:serialization", version.ref = "xmlutil" }
okio = {module = "com.squareup.okio:okio", version.ref = "okio"}

[bundles]
xmlutil = ["xmlutil-core", "xmlutil-serialization"]

[plugins]
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlin" }
kotlin-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlin-kover" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
