[versions]
kotlin = "2.4.0"
kotlin-cli = "0.3.6"
kotlin-io = "0.9.1"
kotlin-kover = "0.9.8"
xmlutil = "1.0.1"
compose-plugin = "1.12.1"
ktlint = "14.2.0"
filekit = "0.16.0"

[libraries]
kotlin-cli = { group = "org.jetbrains.kotlinx", name = "kotlinx-cli", version.ref = "kotlin-cli" }
kotlin-io = { group = "org.jetbrains.kotlinx", name = "kotlinx-io-core", version.ref = "kotlin-io" }
xmlutil-core = { group = "io.github.pdvrieze.xmlutil", name = "core", version.ref = "xmlutil" }
xmlutil-serialization = { group = "io.github.pdvrieze.xmlutil", name = "serialization", version.ref = "xmlutil" }
filekit-dialogs = { module = "io.github.vinceglb:filekit-dialogs", version.ref = "filekit" }
filekit-dialogs-compose = { module = "io.github.vinceglb:filekit-dialogs-compose", version.ref = "filekit" }

[bundles]
xmlutil = ["xmlutil-core", "xmlutil-serialization"]
filekit = ["filekit-dialogs", "filekit-dialogs-compose"]

[plugins]
kotlin-multiplatform = { id = "org.jetbrains.kotlin.multiplatform", version.ref = "kotlin" }
kotlin-kover = { id = "org.jetbrains.kotlinx.kover", version.ref = "kotlin-kover" }
kotlin-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
ktlint = { id = "org.jlleitschuh.gradle.ktlint", version.ref = "ktlint" }
jetbrainsCompose = { id = "org.jetbrains.compose", version.ref = "compose-plugin" }
compose-compiler = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
